### ISSUE TITLE
Confining the pytz version has become a problem

### ISSUE THREAD

**Issue by timcera** [fitnr/convertdate#12]
There are other utilities that when installed or updated will automatically get the latest pytz, which I think is 2018.3.  This creates a dependency problem for convertdate.  This is a request to be able to use the latest pytz version to remove conflicting dependencies between convertdate and other packages.

Kindest regards,
Tim

**Comment by ohadeytan** [comment]
Is there a reason for the requirement **<2018** of `pytz`?
It seems to work fine if I ignore it.

**Comment by fitnr** [comment]
The only reason to confine the version is to ensure that the pytz api doesn't change. The problem here is really pytz, which doesn't use semantic versioning. I've just pushed Convertdate 2.1.3, which should be good through 2020.

People of the future: open a pull request or use convertdate in a virtualenv.
