### ISSUE TITLE
Ordinal is wrong for December 31st

### ISSUE THREAD

**Issue by guyjeangilles** [fitnr/convertdate#34]
`from_gregorian` returns the wrong value for December 31st regardless of the year. The other days of the year seem to work fine. 
```python
>>>import convertdate
>>> convertdate.ordinal.from_gregorian(1, 12, 31)
(1, 0)
>>> convertdate.ordinal.from_gregorian(2, 12, 31)
(2, 0)
>>> convertdate.ordinal.from_gregorian(2, 12, 30)
(2, 364)
>>> convertdate.ordinal.from_gregorian(2020, 12, 31)
(2020, 0)
>>> convertdate.ordinal.from_gregorian(-200, 12, 31)
(-200, 0)
```

I'd be willing to right a patch but I'm unfamiliar with the equation used to find the ordinal. Can someone shed some light? I'd guess the problem is this line:
https://github.com/fitnr/convertdate/blob/001033c6f9db818b13493658aac65f5ea9bc261b/src/convertdate/ordinal.py#L34
Also, there are no tests for this module, which seems wrong. I'd also be willing to write tests if someone can point me to a source for this equation

**Comment by fitnr** [comment]
Much of the code in the repo is inherited from an older package that had limited source info. The equation appears to match the algorithm on the [Wikipedia page](https://en.m.wikipedia.org/wiki/Ordinal_date). If you can write a test that fails that would certainly be appreciated. Otherwise I’ll track it down this week.

**Comment by fitnr** [comment]
This is fixed by the above commit and will be in the next release.
